version: '3.7'
services:
  
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www/src
    volumes:
      - ./:/var/www
      - ./docker_files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #MySQL Service
  database:
    image: mysql:8.0.33
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3304:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - hrm_datas:/var/lib/mysql/
      - ./docker_files/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #PhpMyadmin Networks
  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: database
      #PMA_USER: ${DB_USERNAME}
      #PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8082:80"
    networks:
    - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "800:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker_files/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  hrm_datas:
    driver: local